import { Injectable, signal } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    private languageMap: { [key: string]: string } = {
        'en': 'en', 'en-us': 'en', 'en-gb': 'en', 'en-au': 'en', 'en-ca': 'en', 'en-nz': 'en', 'en-ie': 'en', 'en-za': 'en',
        'ru': 'ru', 'ru-ru': 'ru', 'ru-by': 'ru', 'ru-kz': 'ru',
        'tj': 'tj', 'tg': 'tj', 'tg-tj': 'tj', 'tg-cyrl': 'tj', 'tg-cyrl-tj': 'tj',
        'es': 'es', 'es-es': 'es', 'es-mx': 'es', 'es-ar': 'es', 'es-co': 'es', 'es-pe': 'es', 'es-cl': 'es', 'es-ve': 'es',
        'ar': 'ar', 'ar-sa': 'ar', 'ar-ae': 'ar', 'ar-eg': 'ar', 'ar-dz': 'ar', 'ar-ma': 'ar', 'ar-tn': 'ar', 'ar-sy': 'ar', 'ar-jo': 'ar', 'ar-lb': 'ar', 'ar-kw': 'ar', 'ar-bh': 'ar', 'ar-qa': 'ar', 'ar-om': 'ar', 'ar-ye': 'ar', 'ar-ps': 'ar', 'ar-iq': 'ar',
        'fr': 'fr', 'fr-fr': 'fr', 'fr-ca': 'fr', 'fr-be': 'fr', 'fr-ch': 'fr', 'fr-lu': 'fr', 'fr-ht': 'fr',
        'de': 'de', 'de-de': 'de', 'de-at': 'de', 'de-ch': 'de', 'de-li': 'de', 'de-lu': 'de',
        'zh': 'zh', 'zh-cn': 'zh', 'zh-hans': 'zh', 'zh-hans-cn': 'zh', 'zh-sg': 'zh', 'zh-tw': 'zh', 'zh-hant': 'zh', 'zh-hant-tw': 'zh', 'zh-hk': 'zh', 'zh-mo': 'zh',
        'hi': 'hi', 'hi-in': 'hi', 'hi-latn': 'hi', 'hi-latn-in': 'hi',
        'fa': 'fa', 'fa-ir': 'fa', 'fa-fatn': 'fa', 'fa-fatn-ir': 'fa',
    };

    public currentLang = signal(this.getInitialLanguage());

    private getInitialLanguage(): string {
        const savedLang = localStorage.getItem('lang');
        const supportedCodes = ['en', 'ru', 'tj', 'es', 'ar', 'fr', 'de', 'zh', 'hi', 'fa'];

        if (savedLang && supportedCodes.includes(savedLang)) {
            return savedLang;
        }

        const systemLang = navigator.language.toLowerCase();
        const mappedLang = this.languageMap[systemLang];

        if (mappedLang && supportedCodes.includes(mappedLang)) {
            return mappedLang;
        }

        const baseLang = systemLang.split('-')[0];
        const mappedBaseLang = this.languageMap[baseLang];

        if (mappedBaseLang && supportedCodes.includes(mappedBaseLang)) {
            return mappedBaseLang;
        }

        return 'en';
    }

    private translations: any = {
        'en': {
            'HOME': {
                'TITLE': 'Chatme - Connect with the World',
                'SUBTITLE': 'Find new friends, practice languages, and chat with people across the globe.',
                'START_CHATTING': 'Start Chatting Now',
                'FIND_MATCH': 'Find a Match',
                'FEATURES': 'Features',
                'ABOUT': 'About',
                'HERO_TITLE_PREFIX': 'Connect with people who share your',
                'HERO_TITLE_SUFFIX': 'vibe.',
                'HERO_SUBTITLE': 'Experience real-time random chat with automatic translation and interest matching. Break language barriers and find your tribe.',
                'FEATURE_TRANS_TITLE': 'Real-Time Translation',
                'FEATURE_TRANS_DESC': 'Break language barriers with automatic message translation. Chat with anyone worldwide in your native language.',
                'FEATURE_MATCH_TITLE': 'Smart Matching',
                'FEATURE_MATCH_DESC': 'Our AI-powered algorithm matches you with people who share your interests and vibe for better conversations.',
                'FEATURE_INSTANT_TITLE': 'Instant Connection',
                'FEATURE_INSTANT_DESC': 'Connect with someone new in seconds. No waiting, no algorithms - just pure spontaneous conversation.',
                'FEATURE_PRIVACY_TITLE': 'Privacy First',
                'FEATURE_PRIVACY_DESC': 'Your conversations are encrypted and private. We don\'t store chat history or share your personal data.',
                'FEATURE_TAGS_TITLE': 'Interest Tags',
                'FEATURE_TAGS_DESC': 'Add interest tags to your profile and get matched with people who share your hobbies and passions.',
                'FEATURE_THEME_TITLE': 'Dark/Light Mode',
                'FEATURE_THEME_DESC': 'Choose your preferred theme with beautiful dark and light modes for comfortable chatting any time.',
                'SECTION_FEATURES_TITLE': 'Powerful Features',
                'SECTION_FEATURES_SUB': 'Everything you need for meaningful connections',
                'SECTION_ABOUT_TITLE': 'About Chatme',
                'SECTION_ABOUT_SUB': 'Breaking barriers, building connections',
                'MISSION_TITLE': 'Our Mission',
                'MISSION_DESC': 'Chatme was created with a simple yet powerful vision: to connect people from all walks of life, regardless of language or location. We believe that meaningful conversations can happen anywhere, at any time, between anyone.',
                'JOIN_TITLE': 'Join Our Community',
                'JOIN_DESC': 'Whether you\'re looking to practice a new language, make friends from around the world, or simply have interesting conversations with like-minded people, Chatme is here for you. Join thousands of users who are already breaking barriers and building connections.',
                'CTA_JOIN': 'Start Your Journey',
                'STATS_USERS': 'Active Users',
                'STATS_COUNTRIES': 'Countries',
                'STATS_CONVERSATIONS': 'Conversations',
                'STATS_LANGUAGES': 'Languages',
                'DOWNLOAD_TITLE': 'Get the Chatme app',
                'DOWNLOAD_SUB': 'Stay connected on the go — download our Android or iOS app for the best experience.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'Tip: Scan the QR code (coming soon) to install directly.',
            },
            'AUTH': {
                'WELCOME': 'Welcome to Chatme',
                'SUBTITLE': 'Connect with people who share your vibe',
                'CONTINUE_GOOGLE': 'Continue with Google',
                'CONTINUE_EMAIL': 'Continue with Email',
                'EMAIL_PLACEHOLDER': 'Your email address',
                'CODE_PLACEHOLDER': 'Verification code',
                'SEND_CODE': 'Send code',
                'VERIFY_CODE': 'Verify code',
                'EMAIL_CODE_SENT': 'Verification code sent to your email',
                'SIGNING_IN': 'Signing in...',
                'OR': 'or',
                'REAL_TIME_TRANS': 'Real-time translation',
                'SMART_MATCHING': 'Smart matching',
                'PRIVACY_FIRST': 'Privacy First',
                'TERMS_AGREE': 'By signing in, you agree to our',
                'TERMS': 'Terms',
                'AND': 'and',
                'PRIVACY': 'Privacy Policy'
            },
            'EXPLORE_PAGE': {
                'TITLE': 'Explore Users',
                'FILTERS': 'Filters',
                'RESET': 'Reset',
                'STATUS': 'Status',
                'GENDER': 'Gender',
                'LOCATION': 'Location',
                'NATIVE_LANGUAGE': 'Native Language',
                'LEARNING_LANGUAGE': 'Learning Language',
                'CONNECT_RANDOMLY': 'Connect Randomly',
                'LOADING': 'Loading users...',
                'NO_USERS': 'No users found',
                'NO_USERS_DESC': 'Try adjusting your filters to see more results',
                'RESET_FILTERS': 'Reset Filters',
                'ONLINE': 'Online',
                'OFFLINE': 'Offline',
                'SEND_MESSAGE': 'Send Message',
                'USERS_FOUND': 'users found',
                'USER_FOUND': 'user found',
                'ANY_STATUS': 'Any Status',
                'ONLINE_ONLY': 'Online Only',
                'ANY_GENDER': 'Any Gender',
                'MALE': 'Male',
                'FEMALE': 'Female',
                'ANY_LOCATION': 'Any Location',
                'ANY_LANGUAGE': 'Any Language',
                'NO_RANDOM_USER': 'No users found to connect with! Try again later.',
                'VALIDATION_MESSAGE': 'Please complete your profile information (languages and interests) first to use this feature.',
                'COMPLETE_PROFILE': 'Complete Profile'
            },

            'NAV': {
                'DASHBOARD': 'Dashboard',
                'CHAT': 'Chat',
                'PROFILE': 'Profile',
                'LOGOUT': 'Logout',
                'LOGIN': 'Login',
                'LANGUAGE': 'Language',
                'MESSAGES': 'Messages',
                'EXPLORE': 'Explore',
                'GUESTS': 'Guests',
                'GAMES': 'Games',
                'ADMIN_PANEL': 'Admin Panel',
                'CONTACT_ADMIN': 'Contact Admin',
                'LIGHT_MODE': 'Light Mode',
                'DARK_MODE': 'Dark Mode'
            },
            'PROFILE': {
                'COMPLETE_PROFILE': 'Complete your profile',
                'COMPLETE_PROFILE_DESC': 'Tell us about yourself to find better matches.',
                'ABOUT': 'About',
                'LANGUAGES': 'Languages',
                'NATIVE': 'Native',
                'LEARNING': 'Learning',
                'INTERESTS': 'Interests',
                'COMMENTS_RATINGS': 'Comments & Ratings',
                'RATE_USER': 'Rate this user',
                'WRITE_COMMENT_OPTIONAL': 'Write a comment (optional)...',
                'SUBMIT_RATING': 'Submit Rating',
                'ADD_COMMENT': 'Add a comment',
                'WRITE_COMMENT': 'Write a comment...',
                'ADD_COMMENT_BTN': 'Add Comment',
                'REPLY': 'Reply',
                'SEND': 'Send',
                'SHOW': 'Show',
                'HIDE': 'Hide',
                'REPLIES': 'replies',
                'REPLY_SINGULAR': 'reply',
                'NO_COMMENTS': 'No comments yet.',
                'SEND_MESSAGE': 'Send Message'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'Select a Conversation',
                'START_NOW': 'Start chatting now',
                'WELCOME': 'Welcome to Chatme',
                'WELCOME_SUB': 'Select a conversation or find a new match to start chatting.',
                'TYPE_MESSAGE': 'Type a message...',
                'ONLINE': 'Online',
                'OFFLINE': 'Offline',
                'CHAT_PARTNER': 'Chat Partner',
                'EMPTY_STATE_TITLE': 'Welcome to Chatme',
                'EMPTY_STATE_DESC': 'Select a conversation or find a new match to start chatting.',
                'SEND_IMAGE': 'Send Image',
                'SEND_STICKER': 'Send Sticker',
                'VOICE_MESSAGE': 'Voice Message',
                'RATING_TITLE': 'Rate Experience',
                'RATING_QUESTION': 'How was your conversation?',
                'RATING_COMMENT_PLACEHOLDER': 'Any comments?',
                'SKIP': 'Skip',
                'SUBMIT': 'Submit',
                'REQUEST_TITLE': 'New Chat Request',
                'REQUEST_DESC': 'wants to chat with you!',
                'DECLINE': 'Decline',
                'ACCEPT': 'Accept',
                'FIND_MATCH_TITLE': 'Find Match',
                'GENDER': 'Gender',
                'ANY_GENDER': 'Any Gender',
                'MALE': 'Male',
                'FEMALE': 'Female',
                'LOCATION': 'Location',
                'ANY_LOCATION': 'Any Location',
                'ONLINE_ONLY': 'Online Only',
                'SEARCH': 'Search',
                'RECORDING': 'Recording...',
                'EDITING_MESSAGE': 'Editing message',
                'REPLYING_TO': 'Replying to',
                'LOADING_MESSAGES': 'Loading messages...'
            },
            'DASHBOARD': {
                'ONLINE': 'Online',
                'PROFILE': 'Profile',
                'FIND_MATCH': 'Find Match',
                'STATUS_ONLINE': 'Online'
            },
            'COMMON': {
                'SAVE': 'Save',
                'CANCEL': 'Cancel',
                'CLOSE': 'Close',
                'SUBMIT': 'Submit',
                'SEARCH_PLACEHOLDER': 'Search...',
                'NO_RESULTS': 'No results found'
            },
            'GAMES': {
                'TITLE': 'Games',
                'SUBTITLE': 'Play games with other users and win coins!',
                'CHECKERS': 'Checkers',
                'CHECKERS_DESC': 'Traditional board game. Multi-player & Coins.',
                'PLAY_NOW': 'Play Now',
                'INVITE_RECEIVED': 'wants to play for'
            },
            'CHECKERS': {
                'LOBBY': 'Checkers Lobby',
                'BALANCE': 'Balance',
                'BET_AMOUNT': 'Bet Amount',
                'INVITED_YOU': 'invited you for',
                'ACCEPT': 'Accept',
                'REJECT': 'Reject',
                'ONLINE_PLAYERS': 'Online Players',
                'NO_PLAYERS': 'No other players online...',
                'INVITE': 'Invite',
                'RED': 'Red',
                'BLACK': 'Black',
                'YOUR_TURN': 'YOUR TURN',
                'WAITING': 'WAITING FOR PARTNER...',
                'SEND': 'Send',
                'LEAVE': 'Leave Game',
                'TYPE_MESSAGE': 'Type a message...',
                'VICTORY': 'VICTORY! You won',
                'LOSE': 'LOSE! Better luck next time.',
                'WAITING_ACCEPT': 'Waiting accept'
            }
        },
        'ru': {
            'HOME': {
                'TITLE': 'Chatme - Соединяйтесь с миром',
                'HERO_TITLE_PREFIX': 'Общайтесь с людьми, которые разделяют вашу',
                'HERO_TITLE_SUFFIX': 'атмосферу.',
                'HERO_SUBTITLE': 'Испытайте случайный чат в реальном времени с автоматическим переводом и подбором по интересам.',
                'FEATURE_TRANS_TITLE': 'Перевод в реальном времени',
                'FEATURE_TRANS_DESC': 'Преодолейте языковые барьеры с автоматическим переводом сообщений.',
                'FEATURE_MATCH_TITLE': 'Умный подбор',
                'FEATURE_MATCH_DESC': 'Наш алгоритм подбирает людей, разделяющих ваши интересы.',
                'FEATURE_INSTANT_TITLE': 'Мгновенное соединение',
                'FEATURE_INSTANT_DESC': 'Соединяйтесь с кем-то новым за секунды.',
                'FEATURE_PRIVACY_TITLE': 'Конфиденциальность',
                'FEATURE_PRIVACY_DESC': 'Ваши разговоры зашифрованы и приватны.',
                'FEATURE_TAGS_TITLE': 'Теги интересов',
                'FEATURE_TAGS_DESC': 'Добавьте теги интересов в ваш профиль.',
                'FEATURE_THEME_TITLE': 'Тёмная/Светлая тема',
                'FEATURE_THEME_DESC': 'Выберите предпочтительную тему для комфортного общения.',
                'SECTION_FEATURES_TITLE': 'Мощные функции',
                'SECTION_FEATURES_SUB': 'Всё, что нужно для значимых связей',
                'SECTION_ABOUT_TITLE': 'О Chatme',
                'SECTION_ABOUT_SUB': 'Разрушаем барьеры, строим связи',
                'MISSION_TITLE': 'Наша миссия',
                'MISSION_DESC': 'Chatme был создан с простой, но мощной идеей: соединять людей из всех слоев общества.',
                'JOIN_TITLE': 'Присоединяйтесь к сообществу',
                'JOIN_DESC': 'Ищете ли вы практику нового языка или новых друзей, Chatme для вас.',
                'CTA_JOIN': 'Начать путешествие',
                'START_CHATTING': 'Начать чат',
                'STATS_USERS': 'Активных пользователей',
                'STATS_COUNTRIES': 'Страны',
                'STATS_CONVERSATIONS': 'Разговоров',
                'STATS_LANGUAGES': 'Языков',
                'DOWNLOAD_TITLE': 'Получите приложение Chatme',
                'DOWNLOAD_SUB': 'Оставайтесь на связи — скачайте наше приложение для Android или iOS.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'Совет: отсканируйте QR-код (скоро) для быстрой установки.',
                'FOOTER_RIGHTS': '© 2026 Chatme. Все права защищены.'
            },
            'AUTH': {
                'WELCOME': 'Добро пожаловать в Chatme',
                'SUBTITLE': 'Общайтесь с людьми, которые разделяют ваши интересы',
                'CONTINUE_GOOGLE': 'Войти через Google',
                'SIGNING_IN': 'Вход...',
                'OR': 'или',
                'REAL_TIME_TRANS': 'Мгновенный перевод',
                'SMART_MATCHING': 'Умный подбор',
                'PRIVACY_FIRST': 'Конфиденциальность',
                'TERMS_AGREE': 'Входя в систему, вы соглашаетесь с',
                'TERMS': 'Условиями',
                'AND': 'и',
                'PRIVACY': 'Политикой конфиденциальности'
            },
            'EXPLORE_PAGE': {
                'TITLE': 'Поиск пользователей',
                'FILTERS': 'Фильтры',
                'RESET': 'Сброс',
                'STATUS': 'Статус',
                'GENDER': 'Пол',
                'LOCATION': 'Местоположение',
                'NATIVE_LANGUAGE': 'Родной язык',
                'LEARNING_LANGUAGE': 'Изучаемый язык',
                'CONNECT_RANDOMLY': 'Случайная связь',
                'LOADING': 'Загрузка...',
                'NO_USERS': 'Пользователи не найдены',
                'NO_USERS_DESC': 'Попробуйте изменить фильтры',
                'RESET_FILTERS': 'Сбросить фильтры',
                'ONLINE': 'В сети',
                'OFFLINE': 'Не в сети',
                'SEND_MESSAGE': 'Написать',
                'USERS_FOUND': 'польз. найдено',
                'USER_FOUND': 'польз. найден',
                'ANY_STATUS': 'Любой статус',
                'ONLINE_ONLY': 'Только онлайн',
                'ANY_GENDER': 'Любой пол',
                'MALE': 'Мужской',
                'FEMALE': 'Женский',
                'ANY_LOCATION': 'Любое место',
                'ANY_LANGUAGE': 'Любой язык',
                'NO_RANDOM_USER': 'Не найдено пользователей для связи! Попробуйте позже.',
                'VALIDATION_MESSAGE': 'Пожалуйста, заполните информацию профиля (языки и интересы) перед использованием этой функции.',
                'COMPLETE_PROFILE': 'Заполнить профиль'
            },
            'NAV': {
                'DASHBOARD': 'Панель',
                'CHAT': 'Чат',
                'PROFILE': 'Профиль',
                'LOGOUT': 'Выйти',
                'LOGIN': 'Войти',
                'LANGUAGE': 'Язык',
                'MESSAGES': 'Сообщения',
                'EXPLORE': 'Поиск',
                'GUESTS': 'Гости',
                'GAMES': 'Игры',
                'ADMIN_PANEL': 'Админ панель',
                'CONTACT_ADMIN': 'Связаться с админом',
                'LIGHT_MODE': 'Светлая тема',
                'DARK_MODE': 'Тёмная тема'
            },
            'PROFILE': {
                'ABOUT': 'О себе',
                'LANGUAGES': 'Языки',
                'NATIVE': 'Родной',
                'LEARNING': 'Изучаемый',
                'INTERESTS': 'Интересы',
                'COMMENTS_RATINGS': 'Комментарии и рейтинг',
                'RATE_USER': 'Оценить пользователя',
                'WRITE_COMMENT_OPTIONAL': 'Написать комментарий (необязательно)...',
                'SUBMIT_RATING': 'Отправить оценку',
                'ADD_COMMENT': 'Добавить комментарий',
                'WRITE_COMMENT': 'Написать комментарий...',
                'ADD_COMMENT_BTN': 'Добавить',
                'REPLY': 'Ответить',
                'SEND': 'Отправить',
                'SHOW': 'Показать',
                'HIDE': 'Скрыть',
                'REPLIES': 'ответов',
                'REPLY_SINGULAR': 'ответ',
                'NO_COMMENTS': 'Нет комментариев.',
                'SEND_MESSAGE': 'Отправить сообщение'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'Выберите беседу',
                'START_NOW': 'Начните общаться прямо сейчас',
                'WELCOME': 'Добро пожаловать в Chatme',
                'WELCOME_SUB': 'Выберите беседу или найдите новую пару, чтобы начать чат.',
                'TYPE_MESSAGE': 'Введите сообщение...',
                'ONLINE': 'В сети',
                'OFFLINE': 'Не в сети',
                'CHAT_PARTNER': 'Собеседник',
                'EMPTY_STATE_TITLE': 'Добро пожаловать в Chatme',
                'EMPTY_STATE_DESC': 'Выберите беседу или найдите новую пару.',
                'SEND_IMAGE': 'Отправить фото',
                'SEND_STICKER': 'Отправить стикер',
                'VOICE_MESSAGE': 'Голосовое сообщение',
                'RATING_TITLE': 'Оцените опыт',
                'RATING_QUESTION': 'Как прошел ваш разговор?',
                'RATING_COMMENT_PLACEHOLDER': 'Комментарии?',
                'SKIP': 'Пропустить',
                'SUBMIT': 'Отправить',
                'REQUEST_TITLE': 'Новый запрос чата',
                'REQUEST_DESC': 'хочет пообщаться с вами!',
                'DECLINE': 'Отклонить',
                'ACCEPT': 'Принять',
                'FIND_MATCH_TITLE': 'Найти пару',
                'GENDER': 'Пол',
                'ANY_GENDER': 'Любой пол',
                'MALE': 'Мужской',
                'FEMALE': 'Женский',
                'LOCATION': 'Местоположение',
                'ANY_LOCATION': 'Любое местоположение',
                'ONLINE_ONLY': 'Только онлайн',
                'SEARCH': 'Поиск',
                'RECORDING': 'Запись...',
                'EDITING_MESSAGE': 'Редактирование',
                'REPLYING_TO': 'В ответ на',
                'LOADING_MESSAGES': 'Загрузка сообщений...'
            },
            'DASHBOARD': {
                'ONLINE': 'В сети',
                'PROFILE': 'Профиль',
                'FIND_MATCH': 'Найти пару',
                'STATUS_ONLINE': 'В сети'
            },
            'COMMON': {
                'SAVE': 'Сохранить',
                'CANCEL': 'Отмена',
                'CLOSE': 'Закрыть',
                'SUBMIT': 'Отправить',
                'SEARCH_PLACEHOLDER': 'Поиск...',
                'NO_RESULTS': 'Результаты не найдены'
            },
            'GAMES': {
                'TITLE': 'Игры',
                'SUBTITLE': 'Играйте с другими пользователями и выигрывайте монеты!',
                'CHECKERS': 'Шашки',
                'CHECKERS_DESC': 'Классическая настольная игра. Мультиплеер и монеты.',
                'PLAY_NOW': 'Играть сейчас',
                'INVITE_RECEIVED': 'хочет сыграть на'
            },
            'CHECKERS': {
                'LOBBY': 'Лобби шашек',
                'BALANCE': 'Баланс',
                'BET_AMOUNT': 'Ставка',
                'INVITED_YOU': 'пригласил вас сыграть на',
                'ACCEPT': 'Принять',
                'REJECT': 'Отклонить',
                'ONLINE_PLAYERS': 'Игроки онлайн',
                'NO_PLAYERS': 'Нет других игроков в сети...',
                'INVITE': 'Пригласить',
                'RED': 'Красные',
                'BLACK': 'Черные',
                'YOUR_TURN': 'ВАШ ХОД',
                'WAITING': 'ОЖИДАНИЕ ПАРТНЕРА...',
                'SEND': 'Отправить',
                'LEAVE': 'Выйти из игры',
                'TYPE_MESSAGE': 'Введите сообщение...',
                'VICTORY': 'ПОБЕДА! Вы выиграли',
                'LOSE': 'ПРОИГРЫШ! Повезет в следующий раз.',
                'WAITING_ACCEPT': 'Ожидание принятия'
            }
        },
        'tj': {
            'HOME': {
                'TITLE': 'Chatme - Бо ҷаҳон пайваст шавед',
                'HERO_TITLE_PREFIX': 'Бо одамоне пайваст шавед, ки',
                'HERO_TITLE_SUFFIX': 'ҳамфикри шумоянд.',
                'HERO_SUBTITLE': 'Сӯҳбати тасодуфии воқеӣ бо тарҷумаи автоматӣ ва мувофиқати манфиатҳо.',
                'FEATURE_TRANS_TITLE': 'Тарҷумаи воқеӣ',
                'FEATURE_TRANS_DESC': 'Монеаҳои забониро бо тарҷумаи автоматии паёмҳо бартараф кунед.',
                'FEATURE_MATCH_TITLE': 'Мувофиқати ҳушманд',
                'FEATURE_MATCH_DESC': 'Алгоритми мо шуморо бо одамоне, ки манфиатҳои муштарак доранд, пайваст мекунад.',
                'FEATURE_INSTANT_TITLE': 'Пайвастшавии фаврӣ',
                'FEATURE_INSTANT_DESC': 'Дар сонияҳо бо каси нав пайваст шавед.',
                'FEATURE_PRIVACY_TITLE': 'Махфият дар ҷои аввал',
                'FEATURE_PRIVACY_DESC': 'Сӯҳбатҳои шумо рамзгузорӣ шудаанд ва махфӣ мебошанд.',
                'FEATURE_TAGS_TITLE': 'Тегҳои манфиатҳо',
                'FEATURE_TAGS_DESC': 'Ба профили худ тегҳои манфиатҳоро илова кунед.',
                'FEATURE_THEME_TITLE': 'Реҷаи торик/равшан',
                'FEATURE_THEME_DESC': 'Мавзӯи писандидаи худро интихоб кунед.',
                'SECTION_FEATURES_TITLE': 'Имкониятҳои пурқувват',
                'SECTION_FEATURES_SUB': 'Ҳама чиз барои робитаҳои маънодор',
                'SECTION_ABOUT_TITLE': 'Дар бораи Chatme',
                'SECTION_ABOUT_SUB': 'Бартараф кардани монеаҳо, бунёди робитаҳо',
                'MISSION_TITLE': 'Мақсади мо',
                'MISSION_DESC': 'Chatme барои пайваст кардани одамон аз тамоми табақаҳои ҳаёт сохта шудааст.',
                'JOIN_TITLE': 'Ба ҷамъияти мо ҳамроҳ шавед',
                'JOIN_DESC': 'Хоҳ шумо забони навро омӯхтанӣ бошед, хоҳ дӯстони нав пайдо карданӣ бошед, Chatme барои шумост.',
                'CTA_JOIN': 'Оғози сафар',
                'START_CHATTING': 'Оғози сӯҳбат',
                'STATS_USERS': 'Корбарони фаъол',
                'STATS_COUNTRIES': 'Кишварҳо',
                'STATS_CONVERSATIONS': 'Сӯҳбатҳо',
                'STATS_LANGUAGES': 'Забонҳо',
                'DOWNLOAD_TITLE': 'Барномаи Chatme-ро гиред',
                'DOWNLOAD_SUB': 'Дар ҳаракат нигоҳ доред — барномаи мо барои Android ё iOS-ро зеркашӣ кунед.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'Маслиҳат: QR-кодро скан кунед (ба наздикӣ) барои насби фаврӣ.',
                'FOOTER_RIGHTS': '© 2026 Chatme. Ҳама ҳуқуқ маҳфуз аст.'
            },
            'AUTH': {
                'WELCOME': 'Хуш омадед ба Chatme',
                'SUBTITLE': 'Бо одамоне, ки ҳамфикри шумоянд, пайваст шавед',
                'CONTINUE_GOOGLE': 'Воридшавӣ бо Google',
                'SIGNING_IN': 'Воридшавӣ...',
                'OR': 'ё',
                'REAL_TIME_TRANS': 'Тарҷумаи фаврӣ',
                'SMART_MATCHING': 'Интихоби ҳушманд',
                'PRIVACY_FIRST': 'Махфият',
                'TERMS_AGREE': 'Бо ворид шудан, шумо розӣ мешавед бо',
                'TERMS': 'Шартҳо',
                'AND': 'ва',
                'PRIVACY': 'Сиёсати махфият'
            },
            'EXPLORE_PAGE': {
                'TITLE': 'Ҷустуҷӯи корбарон',
                'FILTERS': 'Филтрҳо',
                'RESET': 'Тоза кардан',
                'STATUS': 'Статус',
                'GENDER': 'Ҷинс',
                'LOCATION': 'Макон',
                'NATIVE_LANGUAGE': 'Забони модарӣ',
                'LEARNING_LANGUAGE': 'Забони омӯзишӣ',
                'CONNECT_RANDOMLY': 'Пайвастшавии тасодуфӣ',
                'LOADING': 'Боргирӣ...',
                'NO_USERS': 'Корбар ёфт нашуд',
                'NO_USERS_DESC': 'Филтрҳоро тағйир диҳед',
                'RESET_FILTERS': 'Тоза кардани филтрҳо',
                'ONLINE': 'Дар шабака',
                'OFFLINE': 'Ғайрифаъол',
                'SEND_MESSAGE': 'Паём навиштан',
                'USERS_FOUND': 'корбар ёфт шуд',
                'USER_FOUND': 'корбар ёфт шуд',
                'ANY_STATUS': 'Ҳар гуна',
                'ONLINE_ONLY': 'Танҳо онлайн',
                'ANY_GENDER': 'Ҳар гуна',
                'MALE': 'Мард',
                'FEMALE': 'Зан',
                'ANY_LOCATION': 'Ҳар ҷо',
                'ANY_LANGUAGE': 'Ҳар гуна',
                'NO_RANDOM_USER': 'Барои пайвастшавӣ корбар ёфт нашуд! Баъдтар кӯшиш кунед.',
                'VALIDATION_MESSAGE': 'Лутфан аввал маълумоти профили худро (забонҳо ва манфиатҳо) пур кунед, то ин хусусиятро истифода баред.',
                'COMPLETE_PROFILE': 'Профилро пур кунед'
            },
            'NAV': {
                'DASHBOARD': 'Панел',
                'CHAT': 'Чат',
                'PROFILE': 'Профил',
                'LOGOUT': 'Баромад',
                'LOGIN': 'Ворид шудан',
                'LANGUAGE': 'Забон',
                'MESSAGES': 'Паёмҳо',
                'EXPLORE': 'Ҷустуҷӯ',
                'GUESTS': 'Меҳмонон',
                'GAMES': 'Бозиҳо',
                'ADMIN_PANEL': 'Панели администратор',
                'CONTACT_ADMIN': 'Тамос бо админ',
                'LIGHT_MODE': 'Реҷаи равшан',
                'DARK_MODE': 'Реҷаи торик'
            },
            'PROFILE': {
                'ABOUT': 'Дар бораи ман',
                'LANGUAGES': 'Забонҳо',
                'NATIVE': 'Модарӣ',
                'LEARNING': 'Омӯхта истодаам',
                'INTERESTS': 'Манфиатҳо',
                'COMMENTS_RATINGS': 'Шарҳҳо ва баҳодиҳӣ',
                'RATE_USER': 'Баҳо додан',
                'WRITE_COMMENT_OPTIONAL': 'Шарҳ нависед (ихтиёрӣ)...',
                'SUBMIT_RATING': 'Фиристодани баҳо',
                'ADD_COMMENT': 'Илова кардани шарҳ',
                'WRITE_COMMENT': 'Шарҳ нависед...',
                'ADD_COMMENT_BTN': 'Илова кардан',
                'REPLY': 'Ҷавоб додан',
                'SEND': 'Равон кардан',
                'SHOW': 'Нишон додан',
                'HIDE': 'Пинҳон кардан',
                'REPLIES': 'ҷавобҳо',
                'REPLY_SINGULAR': 'ҷавоб',
                'NO_COMMENTS': 'Ҳанӯз шарҳ нест.',
                'SEND_MESSAGE': 'Равон кардани паём'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'Сӯҳбатро интихоб кунед',
                'START_NOW': 'Ҳозир ба сӯҳбат оғоз кунед',
                'WELCOME': 'Хуш омадед ба Chatme',
                'WELCOME_SUB': 'Барои оғози сӯҳбат ягон касро интихоб кунед ё ҳамсӯҳбати нав ҷӯед.',
                'TYPE_MESSAGE': 'Паём нависед...',
                'ONLINE': 'Дар шабака',
                'OFFLINE': 'Ғайрифаъол',
                'CHAT_PARTNER': 'Ҳамсӯҳбат',
                'EMPTY_STATE_TITLE': 'Хуш омадед ба Chatme',
                'EMPTY_STATE_DESC': 'Сӯҳбатро интихоб кунед ё ҷуфти нав пайдо кунед.',
                'SEND_IMAGE': 'Равон кардани акс',
                'SEND_STICKER': 'Равон кардани стикер',
                'VOICE_MESSAGE': 'Паёми овозӣ',
                'RATING_TITLE': 'Баҳо диҳед',
                'RATING_QUESTION': 'Сӯҳбат чӣ гуна гузашт?',
                'RATING_COMMENT_PLACEHOLDER': 'Шарҳҳо?',
                'SKIP': 'Гузаштан',
                'SUBMIT': 'Равон кардан',
                'REQUEST_TITLE': 'Дархости нави чат',
                'REQUEST_DESC': 'мехоҳад бо шумо сӯҳбат кунад!',
                'DECLINE': 'Рад кардан',
                'ACCEPT': 'Қабул кардан',
                'FIND_MATCH_TITLE': 'Ҷустуҷӯи ҷуфт',
                'GENDER': 'Ҷинс',
                'ANY_GENDER': 'Ҳар гуна',
                'MALE': 'Мард',
                'FEMALE': 'Зан',
                'LOCATION': 'Макон',
                'ANY_LOCATION': 'Ҳар ҷо',
                'ONLINE_ONLY': 'Танҳо онлайн',
                'SEARCH': 'Ҷустуҷӯ',
                'RECORDING': 'Сабт...'
            },
            'DASHBOARD': {
                'ONLINE': 'Дар шабака',
                'PROFILE': 'Профил',
                'FIND_MATCH': 'Пайдо кардани ҳам‌صحبت',
                'STATUS_ONLINE': 'Дар шабака'
            },
            'COMMON': {
                'SAVE': 'Захира кардан',
                'CANCEL': 'Бекор кардан',
                'CLOSE': 'Пӯшидан',
                'SUBMIT': 'Фиристодан',
                'SEARCH_PLACEHOLDER': 'Ҷустуҷӯ...',
                'NO_RESULTS': 'Натиҷаҳо ёфт нашуданд'
            },
            'GAMES': {
                'TITLE': 'Бозиҳо',
                'SUBTITLE': 'Бо дигар корбарон бозӣ кунед ва тангаҳо ба даст оред!',
                'CHECKERS': 'Шашка',
                'CHECKERS_DESC': 'Бозии классикии рӯи миз. Мултиплеер ва тангаҳо.',
                'PLAY_NOW': 'Бозӣ кардан',
                'INVITE_RECEIVED': 'мехоҳад бозӣ кунад барои'
            },
            'CHECKERS': {
                'LOBBY': 'Лоббии шашка',
                'BALANCE': 'Баланс',
                'BET_AMOUNT': 'Маблағи шарт',
                'INVITED_YOU': 'шуморо даъват кард барои',
                'ACCEPT': 'Қабул',
                'REJECT': 'Рад кардан',
                'ONLINE_PLAYERS': 'Бозингарони онлайн',
                'NO_PLAYERS': 'Дигар бозингарон дар шабака нестанд...',
                'INVITE': 'Даъват кардан',
                'RED': 'Сурх',
                'BLACK': 'Сиёҳ',
                'YOUR_TURN': 'НАВБАТИ ШУМО',
                'WAITING': 'ИНТИЗОРИИ ҲАМСӮҲБАТ...',
                'SEND': 'Равон кардан',
                'LEAVE': 'Баромадан аз бозӣ',
                'TYPE_MESSAGE': 'Паём нависед...',
                'VICTORY': 'ҒАЛАБА! Шумо бурд кардед',
                'LOSE': 'БОХТ! Дафъاи оянда барори кор.',
                'WAITING_ACCEPT': 'Интизори қабул'
            }
        },
        'es': {
            'HOME': {
                'TITLE': 'Chatme - Conecta con el mundo',
                'SUBTITLE': 'Encuentra nuevos amigos, practica idiomas y chatea con personas de todo el mundo.',
                'START_CHATTING': 'Empieza a chatear ahora',
                'FIND_MATCH': 'Encontrar pareja',
                'FEATURES': 'Características',
                'ABOUT': 'Acerca de',
                'HERO_TITLE_PREFIX': 'Conecta con personas que comparten tu',
                'HERO_TITLE_SUFFIX': 'vibración.',
                'HERO_SUBTITLE': 'Experimenta el chat aleatorio en tiempo real con traducción automática y coincidencia de intereses. Rompe las barreras del idioma y encuentra tu tribu.',
                'FEATURE_TRANS_TITLE': 'Traducción en Tiempo Real',
                'FEATURE_TRANS_DESC': 'Rompe las barreras del idioma con la traducción automática de mensajes. Chatea con cualquier persona en todo el mundo en tu idioma nativo.',
                'FEATURE_MATCH_TITLE': 'Coincidencia Inteligente',
                'FEATURE_MATCH_DESC': 'Nuestro algoritmo impulsado por IA te empareja con personas que comparten tus intereses y vibración para mejores conversaciones.',
                'FEATURE_INSTANT_TITLE': 'Conexión Instantánea',
                'FEATURE_INSTANT_DESC': 'Conecta con alguien nuevo en segundos. Sin esperas, sin algoritmos, solo pura conversación espontánea.',
                'FEATURE_PRIVACY_TITLE': 'Privacidad Primero',
                'FEATURE_PRIVACY_DESC': 'Tus conversaciones están encriptadas y son privadas. No almacenamos el historial de chat ni compartimos tus datos personales.',
                'FEATURE_TAGS_TITLE': 'Etiquetas de Interés',
                'FEATURE_TAGS_DESC': 'Agrega etiquetas de interés a tu perfil y sé emparejado con personas que comparten tus pasatiempos y pasiones.',
                'FEATURE_THEME_TITLE': 'Modo Oscuro/Claro',
                'FEATURE_THEME_DESC': 'Elige tu tema preferido con hermosos modos oscuro y claro para chatear cómodamente en cualquier momento.',
                'SECTION_FEATURES_TITLE': 'Características Potentes',
                'SECTION_FEATURES_SUB': 'Todo lo que necesitas para conexiones significativas',
                'SECTION_ABOUT_TITLE': 'Sobre Chatme',
                'SECTION_ABOUT_SUB': 'Rompiendo barreras, construyendo conexiones',
                'MISSION_TITLE': 'Nuestra Misión',
                'MISSION_DESC': 'Chatme fue creado con una visión simple pero poderosa: conectar a personas de todos los ámbitos, independientemente del idioma o la ubicación.',
                'JOIN_TITLE': 'Únete a Nuestra Comunidad',
                'JOIN_DESC': 'Ya sea que busques practicar un nuevo idioma, hacer amigos de todo el mundo o simplemente tener conversaciones interesantes, Chatme es para ti.',
                'CTA_JOIN': 'Comienza Tu Viaje',
                'STATS_USERS': 'Usuarios Activos',
                'STATS_COUNTRIES': 'Países',
                'STATS_CONVERSATIONS': 'Conversaciones',
                'STATS_LANGUAGES': 'Idiomas',
                'DOWNLOAD_TITLE': 'Obtén la aplicación Chatme',
                'DOWNLOAD_SUB': 'Mantente conectado en movimiento — descarga nuestra app para Android o iOS.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'Consejo: Escanea el código QR (próximamente) para instalar directamente.',
                'FOOTER_RIGHTS': '© 2026 Chatme. Todos los derechos reservados.'
            },
            'AUTH': {
                'WELCOME': 'Bienvenido a Chatme',
                'SUBTITLE': 'Conecta con personas que comparten tu vibración',
                'CONTINUE_GOOGLE': 'Continuar con Google',
                'SIGNING_IN': 'Iniciando sesión...',
                'OR': 'o',
                'REAL_TIME_TRANS': 'Traducción en tiempo real',
                'SMART_MATCHING': 'Coincidencia inteligente',
                'PRIVACY_FIRST': 'Privacidad primero',
                'TERMS_AGREE': 'Al iniciar sesión, aceptas nuestros',
                'TERMS': 'Términos',
                'AND': 'y',
                'PRIVACY': 'Política de Privacidad'
            },
            'EXPLORE_PAGE': {
                'TITLE': 'Explorar Usuarios',
                'FILTERS': 'Filtros',
                'RESET': 'Restablecer',
                'STATUS': 'Estado',
                'GENDER': 'Género',
                'LOCATION': 'Ubicación',
                'NATIVE_LANGUAGE': 'Idioma Nativo',
                'LEARNING_LANGUAGE': 'Idioma de Aprendizaje',
                'CONNECT_RANDOMLY': 'Conectar Aleatoriamente',
                'LOADING': 'Cargando usuarios...',
                'NO_USERS': 'No se encontraron usuarios',
                'NO_USERS_DESC': 'Intenta ajustar tus filtros para ver más resultados',
                'RESET_FILTERS': 'Restablecer Filtros',
                'ONLINE': 'En Línea',
                'OFFLINE': 'Desconectado',
                'SEND_MESSAGE': 'Enviar Mensaje',
                'USERS_FOUND': 'usuarios encontrados',
                'USER_FOUND': 'usuario encontrado',
                'ANY_STATUS': 'Cualquier Estado',
                'ONLINE_ONLY': 'Solo En Línea',
                'ANY_GENDER': 'Cualquier Género',
                'MALE': 'Masculino',
                'FEMALE': 'Femenino',
                'ANY_LOCATION': 'Cualquier Ubicación',
                'ANY_LANGUAGE': 'Cualquier Idioma',
                'NO_RANDOM_USER': '¡No se encontraron usuarios para conectar! Inténtalo de nuevo más tarde.',
                'VALIDATION_MESSAGE': 'Por favor, completa tu información de perfil (idiomas e intereses) primero para usar esta función.',
                'COMPLETE_PROFILE': 'Completar perfil'
            },
            'NAV': {
                'DASHBOARD': 'Panel',
                'CHAT': 'Chat',
                'PROFILE': 'Perfil',
                'LOGOUT': 'Cerrar sesión',
                'LOGIN': 'Iniciar sesión',
                'LANGUAGE': 'Idioma',
                'MESSAGES': 'Mensajes',
                'EXPLORE': 'Explorar',
                'GUESTS': 'Invitados',
                'GAMES': 'Juegos',
                'ADMIN_PANEL': 'Panel de Administración',
                'CONTACT_ADMIN': 'Contactar Admin',
                'LIGHT_MODE': 'Modo Claro',
                'DARK_MODE': 'Modo Oscuro'
            },
            'PROFILE': {
                'ABOUT': 'Sobre mí',
                'LANGUAGES': 'Idiomas',
                'NATIVE': 'Nativo',
                'LEARNING': 'Aprendiendo',
                'INTERESTS': 'Intereses',
                'COMMENTS_RATINGS': 'Comentarios y Valoraciones',
                'RATE_USER': 'Calificar usuario',
                'WRITE_COMMENT_OPTIONAL': 'Escribe un comentario (opcional)...',
                'SUBMIT_RATING': 'Enviar Calificación',
                'ADD_COMMENT': 'Agregar comentario',
                'WRITE_COMMENT': 'Escribe un comentario...',
                'ADD_COMMENT_BTN': 'Agregar',
                'REPLY': 'Responder',
                'SEND': 'Enviar',
                'SHOW': 'Mostrar',
                'HIDE': 'Ocultar',
                'REPLIES': 'respuestas',
                'REPLY_SINGULAR': 'respuesta',
                'NO_COMMENTS': 'Aún no hay comentarios.',
                'SEND_MESSAGE': 'Enviar Mensaje'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'Selecciona una conversación',
                'START_NOW': 'Empieza a chatear ahora',
                'WELCOME': 'Bienvenido a Chatme',
                'WELCOME_SUB': 'Selecciona una conversación o busca una nueva coincidencia para empezar a chatear.',
                'TYPE_MESSAGE': 'Escribe un mensaje...',
                'ONLINE': 'En línea',
                'OFFLINE': 'Desconectado',
                'CHAT_PARTNER': 'Compañero de Chat',
                'EMPTY_STATE_TITLE': 'Bienvenido a Chatme',
                'EMPTY_STATE_DESC': 'Selecciona una conversación o busca una nueva coincidencia para empezar a chatear.',
                'SEND_IMAGE': 'Enviar Imagen',
                'SEND_STICKER': 'Enviar Sticker',
                'VOICE_MESSAGE': 'Mensaje de Voz',
                'RATING_TITLE': 'Calificar Experiencia',
                'RATING_QUESTION': '¿Cómo fue tu conversación?',
                'RATING_COMMENT_PLACEHOLDER': '¿Algún comentario?',
                'SKIP': 'Omitir',
                'SUBMIT': 'Enviar',
                'REQUEST_TITLE': 'Nueva Solicitud de Chat',
                'REQUEST_DESC': '¡quiere chatear contigo!',
                'DECLINE': 'Rechazar',
                'ACCEPT': 'Aceptar',
                'FIND_MATCH_TITLE': 'Encontrar Compañero',
                'GENDER': 'Género',
                'LOCATION': 'Ubicación',
                'ANY_LOCATION': 'Cualquier Ubicación',
                'ONLINE_ONLY': 'Solo En Línea',
                'SEARCH': 'Buscar',
                'ANY_GENDER': 'Cualquier Género',
                'MALE': 'Masculino',
                'FEMALE': 'Femenino'
            },
            'DASHBOARD': {
                'ONLINE': 'En línea',
                'PROFILE': 'Perfil',
                'FIND_MATCH': 'Encontrar Compañero',
                'STATUS_ONLINE': 'En línea'
            },
            'COMMON': {
                'SAVE': 'Guardar',
                'CANCEL': 'Cancelar',
                'CLOSE': 'Cerrar',
                'SUBMIT': 'Enviar',
                'SEARCH_PLACEHOLDER': 'Buscar...',
                'NO_RESULTS': 'No se encontraron resultados'
            },
            'GAMES': {
                'TITLE': 'Juegos',
                'SUBTITLE': '¡Juega con otros usuarios y gana monedas!',
                'CHECKERS': 'Damas',
                'CHECKERS_DESC': 'Juego de mesa tradicional. Multijugador y Monedas.',
                'PLAY_NOW': 'Jugar Ahora',
                'INVITE_RECEIVED': 'quiere jugar por'
            },
            'CHECKERS': {
                'LOBBY': 'Lobby de Damas',
                'BALANCE': 'Saldo',
                'BET_AMOUNT': 'Monto de la apuesta',
                'INVITED_YOU': 'te invitó por',
                'ACCEPT': 'Aceptar',
                'REJECT': 'Rechazar',
                'ONLINE_PLAYERS': 'Jugadores en Línea',
                'NO_PLAYERS': 'No hay otros jugadores en línea...',
                'INVITE': 'Invitar',
                'RED': 'Rojo',
                'BLACK': 'Negro',
                'YOUR_TURN': 'TU TURNO',
                'WAITING': 'ESPERANDO AL COMPAÑERO...',
                'SEND': 'Enviar',
                'LEAVE': 'Salir del Juego',
                'TYPE_MESSAGE': 'Escribe un mensaje...',
                'VICTORY': '¡VICTORIA! Ganaste',
                'LOSE': '¡PERDISTE! Mejor suerte la próxima vez.',
                'WAITING_ACCEPT': 'Esperando aceptación'
            }
        },
        'ar': {
            'HOME': {
                'TITLE': 'Chatme - تواصل مع العالم',
                'SUBTITLE': 'ابحث عن أصدقاء جدد، ومارس اللغات، ودردش مع أشخاص من جميع أنحاء العالم.',
                'START_CHATTING': 'ابدأ الدردشة الآن',
                'FIND_MATCH': 'البحث عن صديق',
                'FEATURES': 'المميزات',
                'ABOUT': 'حول',
                'HERO_TITLE_PREFIX': 'تواصل مع أشخاص يشاركونك',
                'HERO_TITLE_SUFFIX': 'اهتماماتك.',
                'HERO_SUBTITLE': 'استمتع بدردشة عشوائية فورية مع ترجمة تلقائية ومطابقة الاهتمامات. اكسر حواجز اللغة واكتشف مجتمعك.',
                'FEATURE_TRANS_TITLE': 'ترجمة فورية',
                'FEATURE_TRANS_DESC': 'اكسر حواجز اللغة مع الترجمة التلقائية للرسائل. دردش مع أي شخص حول العالم بلغتك الأم.',
                'FEATURE_MATCH_TITLE': 'مطابقة ذكية',
                'FEATURE_MATCH_DESC': 'تقوم خوارزمية الذكاء الاصطناعي بمطابقتك مع أشخاص يشاركونك اهتماماتك وأسلوبك لمحادثات أفضل.',
                'FEATURE_INSTANT_TITLE': 'اتصال فوري',
                'FEATURE_INSTANT_DESC': 'تواصل مع شخص جديد في ثوانٍ. بدون انتظار، بدون خوارزميات معقدة - فقط محادثة عفوية.',
                'FEATURE_PRIVACY_TITLE': 'الخصوصية أولاً',
                'FEATURE_PRIVACY_DESC': 'محادثاتك مشفرة وخاصة. نحن لا نخزن سجل المحادثات أو نشارك بياناتك الشخصية.',
                'FEATURE_TAGS_TITLE': 'وسوم الاهتمامات',
                'FEATURE_TAGS_DESC': 'أضف وسوم الاهتمامات إلى ملفك الشخصي ليتم مطابقتك مع أشخاص يشاركونك هواياتك وشغفك.',
                'FEATURE_THEME_TITLE': 'الوضع الداكن/الفاتح',
                'FEATURE_THEME_DESC': 'اختر المظهر المفضل لديك مع أوضاع داكنة وفاتحة جميلة لدردشة مريحة في أي وقت.',
                'SECTION_FEATURES_TITLE': 'ميزات قوية',
                'SECTION_FEATURES_SUB': 'كل ما تحتاجه لاتصالات ذات مغزى',
                'SECTION_ABOUT_TITLE': 'عن Chatme',
                'SECTION_ABOUT_SUB': 'كسر الحواجز، بناء العلاقات',
                'MISSION_TITLE': 'مهتمنا',
                'MISSION_DESC': 'تم إنشاء Chatme برؤية بسيطة ولكنها قوية: ربط الناس من جميع مناحي الحياة، بغض النظر عن اللغة أو الموقع.',
                'JOIN_TITLE': 'انضم إلى مجتمعنا',
                'JOIN_DESC': 'سواء كنت تتطلع لممارسة لغة جديدة، أو تكوين صداقات من جميع أنحاء العالم، فإن Chatme هنا من أجلك.',
                'CTA_JOIN': 'ابدأ رحلتك',
                'STATS_USERS': 'مستخدم نشط',
                'STATS_COUNTRIES': 'بلدان',
                'STATS_CONVERSATIONS': 'محادثات',
                'STATS_LANGUAGES': 'لغات',
                'DOWNLOAD_TITLE': 'احصل على تطبيق Chatme',
                'DOWNLOAD_SUB': 'ابقَ على تواصل أثناء التنقل — حمّل تطبيقنا على Android أو iOS.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'نصيحة: امسح رمز الاستجابة السريعة (QR) لتثبيت مباشر قريبا.',
                'FOOTER_RIGHTS': '© 2025 Chatme. جميع الحقوق محفوظة.'
            },
            'AUTH': {
                'WELCOME': 'مرحباً بك في Chatme',
                'SUBTITLE': 'تواصل مع أشخاص يشاركونك اهتماماتك',
                'CONTINUE_GOOGLE': 'المتابعة باستخدام Google',
                'SIGNING_IN': 'جاري تسجيل الدخول...',
                'OR': 'أو',
                'REAL_TIME_TRANS': 'ترجمة فورية',
                'SMART_MATCHING': 'مطابقة ذكية',
                'PRIVACY_FIRST': 'الخصوصية أولاً',
                'TERMS_AGREE': 'بتسجيل الدخول، أنت توافق على',
                'TERMS': 'شروطنا',
                'AND': 'و',
                'PRIVACY': 'سياسة الخصوصية'
            },
            'EXPLORE_PAGE': {
                'TITLE': 'استكشاف المستخدمين',
                'FILTERS': 'تصفية',
                'RESET': 'إعادة تعيين',
                'STATUS': 'الحالة',
                'GENDER': 'الجنس',
                'LOCATION': 'الموقع',
                'NATIVE_LANGUAGE': 'اللغة الأم',
                'LEARNING_LANGUAGE': 'لغة التعلم',
                'CONNECT_RANDOMLY': 'اتصال عشوائي',
                'LOADING': 'جاري تحميل المستخدمين...',
                'NO_USERS': 'لم يتم العثور على مستخدمين',
                'NO_USERS_DESC': 'حاول تعديل الفلاتر لرؤية المزيد من النتائج',
                'RESET_FILTERS': 'إعادة تعيين الفلاتر',
                'ONLINE': 'متصل',
                'OFFLINE': 'غير متصل',
                'SEND_MESSAGE': 'إرسال رسالة',
                'USERS_FOUND': 'مستخدمين تم العثور عليهم',
                'USER_FOUND': 'مستخدم موجود',
                'ANY_STATUS': 'أي حالة',
                'ONLINE_ONLY': 'متصل فقط',
                'ANY_GENDER': 'أي جنس',
                'MALE': 'ذكر',
                'FEMALE': 'أنثى',
                'ANY_LOCATION': 'أي موقع',
                'ANY_LANGUAGE': 'أي لغة',
                'NO_RANDOM_USER': 'لم يتم العثور على مستخدمين للتواصل معهم! حاول مرة أخرى لاحقًا.',
                'VALIDATION_MESSAGE': 'يرجى إكمال معلومات ملفك الشخصي (اللغات والاهتمامات) أولاً لاستخدام هذه الميزة.',
                'COMPLETE_PROFILE': 'إكمال الملف الشخصي'
            },
            'NAV': {
                'DASHBOARD': 'لوحة التحكم',
                'CHAT': 'الدردشة',
                'PROFILE': 'الملف الشخصي',
                'LOGOUT': 'تسجيل الخروج',
                'LOGIN': 'تسجيل الدخول',
                'LANGUAGE': 'اللغة',
                'MESSAGES': 'الرسائل',
                'EXPLORE': 'استكشاف',
                'GUESTS': 'الضيوف',
                'GAMES': 'الألعاب',
                'ADMIN_PANEL': 'لوحة المشرف',
                'CONTACT_ADMIN': 'الاتصال بالمشرف',
                'LIGHT_MODE': 'الوضع الفاتح',
                'DARK_MODE': 'الوضع الداكن'
            },
            'PROFILE': {
                'ABOUT': 'نبذة عني',
                'LANGUAGES': 'اللغات',
                'NATIVE': 'اللغة الأم',
                'LEARNING': 'تعلم',
                'INTERESTS': 'الاهتمامات',
                'COMMENTS_RATINGS': 'التعليقات والتقييمات',
                'RATE_USER': 'قيم هذا المستخدم',
                'WRITE_COMMENT_OPTIONAL': 'اكتب تعليقاً (اختياري)...',
                'SUBMIT_RATING': 'إرسال التقييم',
                'ADD_COMMENT': 'إضافة تعليق',
                'WRITE_COMMENT': 'اكتب تعليقاً...',
                'ADD_COMMENT_BTN': 'إضافة',
                'REPLY': 'رد',
                'SEND': 'إرسال',
                'SHOW': 'عرض',
                'HIDE': 'إخفاء',
                'REPLIES': 'ردود',
                'REPLY_SINGULAR': 'رد',
                'NO_COMMENTS': 'لا توجد تعليقات بعد.',
                'SEND_MESSAGE': 'إرسال رسالة'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'اختر محادثة',
                'START_NOW': 'ابدأ الدردشة الآن',
                'WELCOME': 'مرحباً بك في Chatme',
                'WELCOME_SUB': 'اختر محادثة أو ابحث عن صديق جديد لبدء الدردشة.',
                'TYPE_MESSAGE': 'اكتب رسالة...',
                'ONLINE': 'متصل',
                'OFFLINE': 'غير متصل',
                'CHAT_PARTNER': 'شريك الدردشة',
                'EMPTY_STATE_TITLE': 'مرحباً بك في Chatme',
                'EMPTY_STATE_DESC': 'اختر محادثة أو ابحث عن صديق جديد لبدء الدردشة.',
                'SEND_IMAGE': 'إرسال صورة',
                'SEND_STICKER': 'إرسال ملصق',
                'VOICE_MESSAGE': 'رسالة صوتية',
                'RATING_TITLE': 'تقييم التجربة',
                'RATING_Question': 'كيف كانت محادثتك؟',
                'RATING_COMMENT_PLACEHOLDER': 'هل لديك أي تعليقات؟',
                'SKIP': 'تخطي',
                'SUBMIT': 'إرسال',
                'REQUEST_TITLE': 'طلب دردشة جديد',
                'REQUEST_DESC': 'يريد الدردشة معك!',
                'DECLINE': 'رفض',
                'ACCEPT': 'قبول',
                'FIND_MATCH_TITLE': 'البحث عن شريك',
                'GENDER': 'الجنس',
                'LOCATION': 'الموقع',
                'ANY_LOCATION': 'أي موقع',
                'ONLINE_ONLY': 'متصل فقط',
                'SEARCH': 'بحث',
                'ANY_GENDER': 'أي جنس',
                'MALE': 'ذكر',
                'FEMALE': 'أنثى'
            },
            'DASHBOARD': {
                'ONLINE': 'متصل',
                'PROFILE': 'الملف الشخصي',
                'FIND_MATCH': 'البحث عن شريك',
                'STATUS_ONLINE': 'متصل'
            },
            'COMMON': {
                'SAVE': 'حفظ',
                'CANCEL': 'إلغاء',
                'CLOSE': 'إغلاق',
                'SUBMIT': 'إرسال',
                'SEARCH_PLACEHOLDER': 'بحث...',
                'NO_RESULTS': 'لا توجد نتائج'
            }
        },
        'fr': {
            'HOME': {
                'TITLE': 'Chatme - Connectez-vous au monde',
                'SUBTITLE': 'Trouvez de nouveaux amis, pratiquez les langues et discutez avec des gens du monde entier.',
                'START_CHATTING': 'Commencez à discuter',
                'FIND_MATCH': 'Trouver un match',
                'FEATURES': 'Fonctionnalités',
                'ABOUT': 'À propos',
                'HERO_TITLE_PREFIX': 'Connectez-vous avec des gens qui partagent votre',
                'HERO_TITLE_SUFFIX': 'vibe.',
                'HERO_SUBTITLE': 'Expérimentez le chat aléatoire en temps réel avec traduction automatique et correspondance des intérêts.',
                'FEATURE_TRANS_TITLE': 'Traduction en Temps Réel',
                'FEATURE_TRANS_DESC': 'Brisez les barrières linguistiques avec la traduction automatique des messages.',
                'FEATURE_MATCH_TITLE': 'Correspondance Intelligente',
                'FEATURE_MATCH_DESC': 'Notre algorithme IA vous met en relation avec des personnes partageant vos intérêts.',
                'FEATURE_INSTANT_TITLE': 'Connexion Instantanée',
                'FEATURE_INSTANT_DESC': 'Connectez-vous avec quelqu\'un de nouveau en quelques secondes.',
                'FEATURE_PRIVACY_TITLE': 'Confidentialité d\'abord',
                'FEATURE_PRIVACY_DESC': 'Vos conversations sont cryptées et privées.',
                'FEATURE_TAGS_TITLE': 'Tags d\'Intérêt',
                'FEATURE_TAGS_DESC': 'Ajoutez des tags d\'intérêt à votre profil.',
                'FEATURE_THEME_TITLE': 'Mode Sombre/Clair',
                'FEATURE_THEME_DESC': 'Choisissez votre thème préféré.',
                'SECTION_FEATURES_TITLE': 'Fonctionnalités Puissantes',
                'SECTION_FEATURES_SUB': 'Tout ce dont vous avez besoin',
                'SECTION_ABOUT_TITLE': 'À propos de Chatme',
                'SECTION_ABOUT_SUB': 'Briser les barrières',
                'MISSION_TITLE': 'Notre Mission',
                'MISSION_DESC': 'Connecter les gens de tous horizons.',
                'JOIN_TITLE': 'Rejoignez Notre Communauté',
                'JOIN_DESC': 'Pratiquez une langue ou faites-vous des amis.',
                'CTA_JOIN': 'Commencez Votre Voyage',
                'STATS_USERS': 'Utilisateurs Actifs',
                'STATS_COUNTRIES': 'Pays',
                'STATS_CONVERSATIONS': 'Conversations',
                'STATS_LANGUAGES': 'Langues',
                'DOWNLOAD_TITLE': 'Obtenez l\'application Chatme',
                'DOWNLOAD_SUB': 'Restez connecté en déplacement — téléchargez notre application Android ou iOS.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'Astuce : scannez le code QR (bientôt) pour installer directement.',
                'FOOTER_RIGHTS': '© 2025 Chatme. Tous droits réservés.'
            },
            'AUTH': {
                'WELCOME': 'Bienvenue sur Chatme',
                'SUBTITLE': 'Connectez-vous avec des gens qui partagent votre vibe',
                'CONTINUE_GOOGLE': 'Continuer avec Google',
                'SIGNING_IN': 'Connexion en cours...',
                'OR': 'ou',
                'REAL_TIME_TRANS': 'Traduction en temps réel',
                'SMART_MATCHING': 'Correspondance intelligente',
                'PRIVACY_FIRST': 'Confidentialité d\'abord',
                'TERMS_AGREE': 'En vous connectant, vous acceptez nos',
                'TERMS': 'Conditions',
                'AND': 'et',
                'PRIVACY': 'Politique de Confidentialité'
            },
            'EXPLORE_PAGE': {
                'TITLE': 'Explorer les Utilisateurs',
                'FILTERS': 'Filtres',
                'RESET': 'Réinitialiser',
                'STATUS': 'Statut',
                'GENDER': 'Genre',
                'LOCATION': 'Localisation',
                'NATIVE_LANGUAGE': 'Langue Maternelle',
                'LEARNING_LANGUAGE': 'Langue d\'Apprentissage',
                'CONNECT_RANDOMLY': 'Connexion Aléatoire',
                'LOADING': 'Chargement des utilisateurs...',
                'NO_USERS': 'Aucun utilisateur trouvé',
                'NO_USERS_DESC': 'Essayez d\'ajuster vos filtres pour voir plus de résultats',
                'RESET_FILTERS': 'Réinitialiser les Filtres',
                'ONLINE': 'En Ligne',
                'OFFLINE': 'Hors Ligne',
                'SEND_MESSAGE': 'Envoyer Message',
                'USERS_FOUND': 'utilisateurs trouvés',
                'USER_FOUND': 'utilisateur trouvé',
                'ANY_STATUS': 'Tout Statut',
                'ONLINE_ONLY': 'En Ligne Uniquement',
                'ANY_GENDER': 'Tout Genre',
                'MALE': 'Homme',
                'FEMALE': 'Femme',
                'ANY_LOCATION': 'Toute Localisation',
                'ANY_LANGUAGE': 'Toute Langue',
                'NO_RANDOM_USER': 'Aucun utilisateur trouvé pour se connecter ! Réessayez plus tard.',
                'VALIDATION_MESSAGE': 'Veuillez d\'abord compléter vos informations de profil (langues et intérêts) pour utiliser cette fonctionnalité.',
                'COMPLETE_PROFILE': 'Compléter le profil'
            },
            'NAV': {
                'DASHBOARD': 'Tableau de bord',
                'CHAT': 'Chat',
                'PROFILE': 'Profil',
                'LOGOUT': 'Déconnexion',
                'LOGIN': 'Connexion',
                'LANGUAGE': 'Langue',
                'MESSAGES': 'Messages',
                'EXPLORE': 'Explorer',
                'GUESTS': 'Invités',
                'GAMES': 'Jeux',
                'ADMIN_PANEL': 'Panneau Admin',
                'CONTACT_ADMIN': 'Contacter Admin',
                'LIGHT_MODE': 'Mode Clair',
                'DARK_MODE': 'Mode Sombre'
            },
            'PROFILE': {
                'ABOUT': 'À propos',
                'LANGUAGES': 'Langues',
                'NATIVE': 'Maternel',
                'LEARNING': 'Apprentissage',
                'INTERESTS': 'Intérêts',
                'COMMENTS_RATINGS': 'Commentaires et Notes',
                'RATE_USER': 'Noter l\'utilisateur',
                'WRITE_COMMENT_OPTIONAL': 'Écrire un commentaire...',
                'SUBMIT_RATING': 'Envoyer',
                'ADD_COMMENT': 'Ajouter un commentaire',
                'WRITE_COMMENT': 'Écrire un commentaire...',
                'ADD_COMMENT_BTN': 'Ajouter',
                'REPLY': 'Répondre',
                'SEND': 'Envoyer',
                'SHOW': 'Afficher',
                'HIDE': 'Masquer',
                'REPLIES': 'réponses',
                'REPLY_SINGULAR': 'réponse',
                'NO_COMMENTS': 'Aucun commentaire.',
                'SEND_MESSAGE': 'Envoyer Message'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'Sélectionnez une conversation',
                'START_NOW': 'Commencez à discuter',
                'WELCOME': 'Bienvenue sur Chatme',
                'WELCOME_SUB': 'Sélectionnez une conversation ou trouvez un nouveau match.',
                'TYPE_MESSAGE': 'Écrivez un message...',
                'ONLINE': 'En ligne',
                'OFFLINE': 'Hors ligne',
                'CHAT_PARTNER': 'Partenaire de Chat',
                'EMPTY_STATE_TITLE': 'Bienvenue sur Chatme',
                'EMPTY_STATE_DESC': 'Commencez une nouvelle conversation.',
                'SEND_IMAGE': 'Envoyer Image',
                'SEND_STICKER': 'Envoyer Sticker',
                'VOICE_MESSAGE': 'Message Vocal',
                'RATING_TITLE': 'Notez l\'expérience',
                'RATING_Question': 'Comment était votre conversation ?',
                'RATING_COMMENT_PLACEHOLDER': 'Des commentaires ?',
                'SKIP': 'Passer',
                'SUBMIT': 'Envoyer',
                'REQUEST_TITLE': 'Nouvelle Demande',
                'REQUEST_DESC': 'veut discuter avec vous !',
                'DECLINE': 'Refuser',
                'ACCEPT': 'Accepter',
                'FIND_MATCH_TITLE': 'Trouver un Partenaire',
                'GENDER': 'Genre',
                'LOCATION': 'Localisation',
                'ANY_LOCATION': 'Toute Localisation',
                'ONLINE_ONLY': 'En Ligne Uniquement',
                'SEARCH': 'Chercher',
                'ANY_GENDER': 'Tout Genre',
                'MALE': 'Homme',
                'FEMALE': 'Femme'
            },
            'DASHBOARD': {
                'ONLINE': 'En ligne',
                'PROFILE': 'Profil',
                'FIND_MATCH': 'Trouver un match',
                'STATUS_ONLINE': 'En ligne'
            },
            'COMMON': {
                'SAVE': 'Sauvegarder',
                'CANCEL': 'Annuler',
                'CLOSE': 'Fermer',
                'SUBMIT': 'Soumettre',
                'SEARCH_PLACEHOLDER': 'Rechercher...',
                'NO_RESULTS': 'Aucun résultat'
            }
        },
        'de': {
            'HOME': {
                'TITLE': 'Chatme - Verbinde dich mit der Welt',
                'SUBTITLE': 'Finde neue Freunde und übe Sprachen.',
                'START_CHATTING': 'Jetzt chatten',
                'FIND_MATCH': 'Match finden',
                'FEATURES': 'Funktionen',
                'ABOUT': 'Über uns',
                'HERO_TITLE_PREFIX': 'Verbinde dich mit Leuten, die deinen',
                'HERO_TITLE_SUFFIX': 'Vibe teilen.',
                'HERO_SUBTITLE': 'Erlebe Echtzeit-Chat mit automatischer Übersetzung.',
                'FEATURE_TRANS_TITLE': 'Echtzeit-Übersetzung',
                'FEATURE_TRANS_DESC': 'Überwinde Sprachbarrieren.',
                'FEATURE_MATCH_TITLE': 'Smart Matching',
                'FEATURE_MATCH_DESC': 'Unser KI-Algorithmus findet passende Partner.',
                'FEATURE_INSTANT_TITLE': 'Sofortige Verbindung',
                'FEATURE_INSTANT_DESC': 'Verbinde dich in Sekunden.',
                'FEATURE_PRIVACY_TITLE': 'Privatsphäre zuerst',
                'FEATURE_PRIVACY_DESC': 'Deine Gespräche sind verschlüsselt.',
                'FEATURE_TAGS_TITLE': 'Interessens-Tags',
                'FEATURE_TAGS_DESC': 'Füge Tags zu deinem Profil hinzu.',
                'FEATURE_THEME_TITLE': 'Dunkel-/Hellmodus',
                'FEATURE_THEME_DESC': 'Wähle dein bevorzugtes Design.',
                'SECTION_FEATURES_TITLE': 'Mächtige Funktionen',
                'SECTION_FEATURES_SUB': 'Alles was du brauchst',
                'SECTION_ABOUT_TITLE': 'Über Chatme',
                'SECTION_ABOUT_SUB': 'Verbindungen aufbauen',
                'MISSION_TITLE': 'Unsere Mission',
                'MISSION_DESC': 'Menschen verbinden.',
                'JOIN_TITLE': 'Tritt bei',
                'JOIN_DESC': 'Übe Sprachen und finde Freunde.',
                'CTA_JOIN': 'Starte jetzt',
                'STATS_USERS': 'Aktive Nutzer',
                'STATS_COUNTRIES': 'Länder',
                'STATS_CONVERSATIONS': 'Unterhaltungen',
                'STATS_LANGUAGES': 'Sprachen',
                'DOWNLOAD_TITLE': 'Hol dir die Chatme-App',
                'DOWNLOAD_SUB': 'Bleib unterwegs verbunden — lade unsere Android- oder iOS-App herunter.',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'Tipp: Scanne den QR-Code (kommt bald), um direkt zu installieren.',
                'FOOTER_RIGHTS': '© 2025 Chatme. Alle Rechte vorbehalten.'
            },
            'AUTH': {
                'WELCOME': 'Willkommen bei Chatme',
                'SUBTITLE': 'Verbinde dich mit Leuten, die deinen Vibe teilen',
                'CONTINUE_GOOGLE': 'Mit Google fortfahren',
                'SIGNING_IN': 'Anmelden...',
                'OR': 'oder',
                'REAL_TIME_TRANS': 'Echtzeit-Übersetzung',
                'SMART_MATCHING': 'Smart Matching',
                'PRIVACY_FIRST': 'Privatsphäre zuerst',
                'TERMS_AGREE': 'Durch die Anmeldung stimmst du unseren zu',
                'TERMS': 'AGB',
                'AND': 'und',
                'PRIVACY': 'Datenschutzrichtlinie'
            },
            'NAV': {
                'DASHBOARD': 'Dashboard',
                'CHAT': 'Chat',
                'PROFILE': 'Profil',
                'LOGOUT': 'Abmelden',
                'LOGIN': 'Anmelden',
                'LANGUAGE': 'Sprache',
                'MESSAGES': 'Nachrichten',
                'EXPLORE': 'Erkunden',
                'GUESTS': 'Gäste',
                'GAMES': 'Spiele',
                'ADMIN_PANEL': 'Admin-Panel',
                'CONTACT_ADMIN': 'Admin kontaktieren',
                'LIGHT_MODE': 'Heller Modus',
                'DARK_MODE': 'Dunkler Modus'
            },
            'PROFILE': {
                'ABOUT': 'Über mich',
                'LANGUAGES': 'Sprachen',
                'NATIVE': 'Muttersprache',
                'LEARNING': 'Lernend',
                'INTERESTS': 'Interessen',
                'COMMENTS_RATINGS': 'Kommentare & Bewertungen',
                'RATE_USER': 'Benutzer bewerten',
                'WRITE_COMMENT_OPTIONAL': 'Schreibe einen Kommentar...',
                'SUBMIT_RATING': 'Bewertung senden',
                'ADD_COMMENT': 'Kommentar hinzufügen',
                'WRITE_COMMENT': 'Kommentar schreiben...',
                'ADD_COMMENT_BTN': 'Hinzufügen',
                'REPLY': 'Antworten',
                'SEND': 'Senden',
                'SHOW': 'Anzeigen',
                'HIDE': 'Ausblenden',
                'REPLIES': 'Antworten',
                'REPLY_SINGULAR': 'Antwort',
                'NO_COMMENTS': 'Keine Kommentare.',
                'SEND_MESSAGE': 'Nachricht senden'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'Wähle eine Unterhaltung',
                'START_NOW': 'Jetzt chatten',
                'WELCOME': 'Willkommen bei Chatme',
                'WELCOME_SUB': 'Finde einen neuen Match.',
                'TYPE_MESSAGE': 'Nachricht schreiben...',
                'ONLINE': 'Online',
                'OFFLINE': 'Offline',
                'CHAT_PARTNER': 'Chat-Partner',
                'EMPTY_STATE_TITLE': 'Willkommen',
                'EMPTY_STATE_DESC': 'Starte einen Chat.',
                'SEND_IMAGE': 'Bild senden',
                'SEND_STICKER': 'Sticker senden',
                'VOICE_MESSAGE': 'Sprachnachricht',
                'RATING_TITLE': 'Bewerten',
                'RATING_Question': 'Wie war das Gespräch?',
                'RATING_COMMENT_PLACEHOLDER': 'Kommentare?',
                'SKIP': 'Überspringen',
                'SUBMIT': 'Senden',
                'REQUEST_TITLE': 'Neue Anfrage',
                'REQUEST_DESC': 'möchte chatten!',
                'DECLINE': 'Ablehnen',
                'ACCEPT': 'Annehmen',
                'FIND_MATCH_TITLE': 'Partner finden',
                'GENDER': 'Geschlecht',
                'LOCATION': 'Ort',
                'ANY_LOCATION': 'Jeder Ort',
                'ONLINE_ONLY': 'Nur Online',
                'SEARCH': 'Suchen',
                'ANY_GENDER': 'Jedes Geschlecht',
                'MALE': 'Männlich',
                'FEMALE': 'Weiblich',
                'VALIDATION_MESSAGE': 'Bitte vervollständigen Sie zuerst Ihre Profilinformationen (Sprachen und Interessen), um diese Funktion nutzen zu können.',
                'COMPLETE_PROFILE': 'Profil vervollständigen'
            },
            'DASHBOARD': {
                'ONLINE': 'Online',
                'PROFILE': 'Profil',
                'FIND_MATCH': 'Partner finden',
                'STATUS_ONLINE': 'Online'
            },
            'COMMON': {
                'SAVE': 'Speichern',
                'CANCEL': 'Abbrechen',
                'CLOSE': 'Schließen',
                'SUBMIT': 'Senden',
                'SEARCH_PLACEHOLDER': 'Suchen...',
                'NO_RESULTS': 'Keine Ergebnisse'
            }
        },
        'zh': {
            'HOME': {
                'TITLE': 'Chatme - 与世界联系',
                'SUBTITLE': '寻找新朋友，练习语言，并与世界各地的人聊天。',
                'START_CHATTING': '开始聊天',
                'FIND_MATCH': '寻找匹配',
                'FEATURES': '功能',
                'ABOUT': '关于',
                'HERO_TITLE_PREFIX': '连接与你分享',
                'HERO_TITLE_SUFFIX': '氛围的人。',
                'HERO_SUBTITLE': '体验带有自动翻译和兴趣匹配的实时随机聊天。',
                'FEATURE_TRANS_TITLE': '实时翻译',
                'FEATURE_TRANS_DESC': '通过自动消息翻译打破语言障碍。',
                'FEATURE_MATCH_TITLE': '智能匹配',
                'FEATURE_MATCH_DESC': '我们的AI算法为你匹配志同道合的人。',
                'FEATURE_INSTANT_TITLE': '即时连接',
                'FEATURE_INSTANT_DESC': '几秒钟内连接新朋友。',
                'FEATURE_PRIVACY_TITLE': '隐私至上',
                'FEATURE_PRIVACY_DESC': '你的对话是加密和私密的。',
                'FEATURE_TAGS_TITLE': '兴趣标签',
                'FEATURE_TAGS_DESC': '在你的个人资料中添加兴趣标签。',
                'FEATURE_THEME_TITLE': '深色/浅色模式',
                'FEATURE_THEME_DESC': '选择你喜欢的主题。',
                'SECTION_FEATURES_TITLE': '强大功能',
                'SECTION_FEATURES_SUB': '建立有意义连接所需的一切',
                'SECTION_ABOUT_TITLE': '关于 Chatme',
                'SECTION_ABOUT_SUB': '打破障碍，建立连接',
                'MISSION_TITLE': '我们的使命',
                'MISSION_DESC': '连接各行各业的人们。',
                'JOIN_TITLE': '加入我们的社区',
                'JOIN_DESC': '练习新语言或结交世界各地的朋友。',
                'CTA_JOIN': '开始旅程',
                'STATS_USERS': '活跃用户',
                'STATS_COUNTRIES': '国家',
                'STATS_CONVERSATIONS': '对话',
                'STATS_LANGUAGES': '语言',
                'DOWNLOAD_TITLE': '获取 Chatme 应用',
                'DOWNLOAD_SUB': '随时随地保持连接 — 下载我们的 Android 或 iOS 应用。',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': '提示：扫描二维码（即将推出）以直接安装。',
                'FOOTER_RIGHTS': '© 2025 Chatme. 保留所有权利。'
            },
            'AUTH': {
                'WELCOME': '欢迎来到 Chatme',
                'SUBTITLE': '连接与你志同道合的人',
                'CONTINUE_GOOGLE': '使用 Google 继续',
                'SIGNING_IN': '登录中...',
                'OR': '或',
                'REAL_TIME_TRANS': '实时翻译',
                'SMART_MATCHING': '智能匹配',
                'PRIVACY_FIRST': '隐私至上',
                'TERMS_AGREE': '登录即表示您同意我们的',
                'TERMS': '条款',
                'AND': '和',
                'PRIVACY': '隐私政策'
            },
            'NAV': {
                'DASHBOARD': '仪表盘',
                'CHAT': '聊天',
                'PROFILE': '个人资料',
                'LOGOUT': '登出',
                'LOGIN': '登录',
                'LANGUAGE': '语言',
                'MESSAGES': '消息',
                'EXPLORE': '探索',
                'GUESTS': '访客',
                'GAMES': '游戏',
                'ADMIN_PANEL': '管理面板',
                'CONTACT_ADMIN': '联系管理员',
                'LIGHT_MODE': '浅色模式',
                'DARK_MODE': '深色模式'
            },
            'PROFILE': {
                'ABOUT': '关于我',
                'LANGUAGES': '语言',
                'NATIVE': '母语',
                'LEARNING': '学习中',
                'INTERESTS': '兴趣',
                'COMMENTS_RATINGS': '评论和评分',
                'RATE_USER': '评价此用户',
                'WRITE_COMMENT_OPTIONAL': '写评论（可选）...',
                'SUBMIT_RATING': '提交评分',
                'ADD_COMMENT': '添加评论',
                'WRITE_COMMENT': '写评论...',
                'ADD_COMMENT_BTN': '添加',
                'REPLY': '回复',
                'SEND': '发送',
                'SHOW': '显示',
                'HIDE': '隐藏',
                'REPLIES': '回复',
                'REPLY_SINGULAR': '回复',
                'NO_COMMENTS': '暂无评论。',
                'SEND_MESSAGE': '发送消息'
            },
            'CHAT': {
                'SELECT_CONVERSATION': '选择对话',
                'START_NOW': '开始聊天',
                'WELCOME': '欢迎来到 Chatme',
                'WELCOME_SUB': '选择对话或寻找新匹配。',
                'TYPE_MESSAGE': '输入消息...',
                'ONLINE': '在线',
                'OFFLINE': '离线',
                'CHAT_PARTNER': '聊天伙伴',
                'EMPTY_STATE_TITLE': '欢迎',
                'EMPTY_STATE_DESC': '开始新的对话。',
                'SEND_IMAGE': '发送图片',
                'SEND_STICKER': '发送表情',
                'VOICE_MESSAGE': '语音消息',
                'RATING_TITLE': '评价体验',
                'RATING_Question': '对话即使如何？',
                'RATING_COMMENT_PLACEHOLDER': '有何评论？',
                'SKIP': '跳过',
                'SUBMIT': '提交',
                'REQUEST_TITLE': '新聊天请求',
                'REQUEST_DESC': '想和你聊天！',
                'DECLINE': '拒绝',
                'ACCEPT': '接受',
                'FIND_MATCH_TITLE': '寻找伙伴',
                'GENDER': '性别',
                'LOCATION': '位置',
                'ANY_LOCATION': '任意位置',
                'ONLINE_ONLY': '仅在线',
                'SEARCH': '搜索',
                'ANY_GENDER': '任意性别',
                'MALE': '男',
                'FEMALE': '女',
                'VALIDATION_MESSAGE': '请先完善您的个人资料（语言和兴趣）以使用此功能。',
                'COMPLETE_PROFILE': '完善个人资料'
            },
            'DASHBOARD': {
                'ONLINE': '在线',
                'PROFILE': '个人资料',
                'FIND_MATCH': '寻找匹配',
                'STATUS_ONLINE': '在线'
            },
            'COMMON': {
                'SAVE': '保存',
                'CANCEL': '取消',
                'CLOSE': '关闭',
                'SUBMIT': '提交',
                'SEARCH_PLACEHOLDER': '搜索...',
                'NO_RESULTS': '无结果'
            }
        },
        'hi': {
            'HOME': {
                'TITLE': 'Chatme - दुनिया से जुड़ें',
                'SUBTITLE': 'नए दोस्त खोजें, भाषाओं का अभ्यास करें।',
                'START_CHATTING': 'चैट शुरू करें',
                'FIND_MATCH': 'मैच खोजें',
                'FEATURES': 'विशेषताएं',
                'ABOUT': 'हमारे बारे में',
                'HERO_TITLE_PREFIX': 'उन लोगों से जुड़ें जो आपकी',
                'HERO_TITLE_SUFFIX': 'वाइब साझा करते हैं।',
                'HERO_SUBTITLE': 'स्वचालित अनुवाद के साथ रीयल-टाइम चैट का अनुभव करें।',
                'FEATURE_TRANS_TITLE': 'रीयल-टाइम अनुवाद',
                'FEATURE_TRANS_DESC': 'भाषा की बाधाओं को तोड़ें।',
                'FEATURE_MATCH_TITLE': 'स्मार्ट मैचिंग',
                'FEATURE_MATCH_DESC': 'हमारा एआई एल्गोरिदम आपको सही लोगों से मिलाता है।',
                'FEATURE_INSTANT_TITLE': 'त्वरित कनेक्शन',
                'FEATURE_INSTANT_DESC': 'सेकंड में किसी नए व्यक्ति से जुड़ें।',
                'FEATURE_PRIVACY_TITLE': 'गोपनीयता पहले',
                'FEATURE_PRIVACY_DESC': 'आपकी बातचीत एन्क्रिप्टेड है।',
                'FEATURE_TAGS_TITLE': 'रुचि टैग',
                'FEATURE_TAGS_DESC': 'अपनी प्रोफ़ाइल में रुचि टैग जोड़ें।',
                'FEATURE_THEME_TITLE': 'डार्क/लाइट मोड',
                'FEATURE_THEME_DESC': 'अपनी पसंदीदा थीम चुनें।',
                'SECTION_FEATURES_TITLE': 'शक्तिशाली विशेषताएं',
                'SECTION_FEATURES_SUB': 'सार्थक कनेक्शन के लिए आपको जो कुछ भी चाहिए',
                'SECTION_ABOUT_TITLE': 'Chatme के बारे में',
                'SECTION_ABOUT_SUB': 'बाधाओं को तोड़ना',
                'MISSION_TITLE': 'हमारा मिशन',
                'MISSION_DESC': 'लोगों को जोड़ना।',
                'JOIN_TITLE': 'हमारे समुदाय में शामिल हों',
                'JOIN_DESC': 'नई भाषा का अभ्यास करें या दोस्त बनाएं।',
                'CTA_JOIN': 'यात्रा शुरू करें',
                'STATS_USERS': 'सक्रिय उपयोगकर्ता',
                'STATS_COUNTRIES': 'देश',
                'STATS_CONVERSATIONS': 'बातचीत',
                'STATS_LANGUAGES': 'भाषाएं',
                'DOWNLOAD_TITLE': 'Chatme ऐप प्राप्त करें',
                'DOWNLOAD_SUB': 'चलते-फिरते जुड़े रहें — हमारे Android या iOS ऐप को डाउनलोड करें।',
                'DOWNLOAD_ANDROID': 'Android',
                'DOWNLOAD_IPHONE': 'iPhone',
                'DOWNLOAD_NOTE': 'सलाह: सीधे इंस्टॉल करने के लिए QR कोड स्कैन करें (शिग्घ्र)।',
                'FOOTER_RIGHTS': '© 2025 Chatme. सर्वाधिकार सुरक्षित।'
            },
            'AUTH': {
                'WELCOME': 'Chatme में आपका स्वागत है',
                'SUBTITLE': 'उन लोगों से जुड़ें जो आपकी वाइब साझा करते हैं',
                'CONTINUE_GOOGLE': 'Google के साथ जारी रखें',
                'SIGNING_IN': 'साइन इन हो रहा है...',
                'OR': 'या',
                'REAL_TIME_TRANS': 'रीयल-टाइम अनुवाद',
                'SMART_MATCHING': 'स्मार्ट मैचिंग',
                'PRIVACY_FIRST': 'गोपनीयता पहले',
                'TERMS_AGREE': 'साइन इन करके, आप हमारी सहमत होते हैं',
                'TERMS': 'शर्तें',
                'AND': 'और',
                'PRIVACY': 'गोपनीयता नीति'
            },
            'NAV': {
                'DASHBOARD': 'डैशबोर्ड',
                'CHAT': 'चैट',
                'PROFILE': 'प्रोफ़ाइल',
                'LOGOUT': 'लॉग आउट',
                'LOGIN': 'लॉग इन',
                'LANGUAGE': 'भाषा',
                'MESSAGES': 'संदेश',
                'EXPLORE': 'एक्सप्लोर',
                'GUESTS': 'अतिथि',
                'GAMES': 'खेल',
                'ADMIN_PANEL': 'एडमिन पैनल',
                'CONTACT_ADMIN': 'एडमिन से संपर्क करें',
                'LIGHT_MODE': 'लाइट मोड',
                'DARK_MODE': 'डार्क मोड'
            },
            'PROFILE': {
                'ABOUT': 'मेरे बारे में',
                'LANGUAGES': 'भाषाएं',
                'NATIVE': 'मातृभाषा',
                'LEARNING': 'सीख रहे हैं',
                'INTERESTS': 'रुचियां',
                'COMMENTS_RATINGS': 'टिप्पणियाँ और रेटिंग',
                'RATE_USER': 'उपयोगकर्ता को रेट करें',
                'WRITE_COMMENT_OPTIONAL': 'टिप्पणी लिखें...',
                'SUBMIT_RATING': 'रेटिंग भेजें',
                'ADD_COMMENT': 'टिप्पणी जोड़ें',
                'WRITE_COMMENT': 'टिप्पणी लिखें...',
                'ADD_COMMENT_BTN': 'जोड़ें',
                'REPLY': 'उत्तर दें',
                'SEND': 'भेजें',
                'SHOW': 'दिखाएं',
                'HIDE': 'छिपाएं',
                'REPLIES': 'उत्तर',
                'REPLY_SINGULAR': 'उत्तर',
                'NO_COMMENTS': 'अभी तक कोई टिप्पणी नहीं।',
                'SEND_MESSAGE': 'संदेश भेजें'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'बातचीत चुनें',
                'START_NOW': 'चैट शुरू करें',
                'WELCOME': 'Chatme में आपका स्वागत है',
                'WELCOME_SUB': 'बातचीत चुनें या नया मैच खोजें।',
                'TYPE_MESSAGE': 'संदेश लिखें...',
                'ONLINE': 'ऑनलाइन',
                'OFFLINE': 'ऑफलाइन',
                'CHAT_PARTNER': 'चैट पार्टनर',
                'EMPTY_STATE_TITLE': 'स्वागत है',
                'EMPTY_STATE_DESC': 'बातचीत शुरू करें।',
                'SEND_IMAGE': 'छवि भेजें',
                'SEND_STICKER': 'स्टिकर भेजें',
                'VOICE_MESSAGE': 'वॉयस मैसेज',
                'RATING_TITLE': 'अनुभव को रेट करें',
                'RATING_Question': 'बातचीत कैसी रही?',
                'RATING_COMMENT_PLACEHOLDER': 'कोई टिप्पणी?',
                'SKIP': 'छोड़ें',
                'SUBMIT': 'भेजें',
                'REQUEST_TITLE': 'नई चैट अनुरोध',
                'REQUEST_DESC': 'आपसे चैट करना चाहता है!',
                'DECLINE': 'अस्वीकार करें',
                'ACCEPT': 'स्वीकार करें',
                'FIND_MATCH_TITLE': 'साथी खोजें',
                'GENDER': 'लिंग',
                'LOCATION': 'स्थान',
                'ANY_LOCATION': 'कोई भी स्थान',
                'ONLINE_ONLY': 'केवल ऑनलाइन',
                'SEARCH': 'खोजें',
                'ANY_GENDER': 'कोई भी लिंग',
                'MALE': 'पुरुष',
                'FEMALE': 'महिला',
                'VALIDATION_MESSAGE': 'इस सुविधा का उपयोग करने के लिए कृपया पहले अपनी प्रोफ़ाइल जानकारी (भाषाएं और रुचियां) पूरी करें।',
                'COMPLETE_PROFILE': 'प्रोफ़ाइल पूरी करें'
            },
            'DASHBOARD': {
                'ONLINE': 'ऑनलाइन',
                'PROFILE': 'प्रोफ़ाइल',
                'FIND_MATCH': 'मैच खोजें',
                'STATUS_ONLINE': 'ऑनलाइन'
            },
            'COMMON': {
                'SAVE': 'सहेजें',
                'CANCEL': 'रद्द करें',
                'CLOSE': 'बंद करें',
                'SUBMIT': 'भेजें',
                'SEARCH_PLACEHOLDER': 'खोजें...',
                'NO_RESULTS': 'कोई परिणाम नहीं'
            }
        },
        'fa': {
            'HOME': {
                'TITLE': 'Chatme - با جهان ارتباط برقرار کنید',
                'SUBTITLE': 'دوستان جدید پیدا کنید، زبان‌ها را تمرین کنید و با مردم سراسر جهان گفتگو کنید.',
                'START_CHATTING': 'شروع گفتگو',
                'FIND_MATCH': 'یافتن دوست',
                'FEATURES': 'ویژگی‌ها',
                'ABOUT': 'درباره ما',
                'HERO_TITLE_PREFIX': 'با افرادی که',
                'HERO_TITLE_SUFFIX': 'هم‌فرکانس شما هستند ارتباط برقرار کنید.',
                'HERO_SUBTITLE': 'تجربه چت تصادفی بلادرنگ با ترجمه خودکار و تطبیق علایق. موانع زبانی را بشکنید و قبیله خود را پیدا کنید.',
                'FEATURE_TRANS_TITLE': 'ترجمه بلادرنگ',
                'FEATURE_TRANS_DESC': 'موانع زبانی را با ترجمه خودکار پیام‌ها بشکنید. با هر کسی در سراسر جهان به زبان مادری خود صحبت کنید.',
                'FEATURE_MATCH_TITLE': 'تطبیق هوشمند',
                'FEATURE_MATCH_DESC': 'الگوریتم هوشمند ما شما را با افرادی که علایق مشترک دارند تطبیق می‌دهد.',
                'FEATURE_INSTANT_TITLE': 'ارتباط فوری',
                'FEATURE_INSTANT_DESC': 'در چند ثانیه با فردی جدید ارتباط برقرار کنید.',
                'FEATURE_PRIVACY_TITLE': 'اول حریم خصوصی',
                'FEATURE_PRIVACY_DESC': 'گفتگوهای شما رمزگذاری شده و خصوصی هستند.',
                'FEATURE_TAGS_TITLE': 'برچسب‌های علایق',
                'FEATURE_TAGS_DESC': 'برچسب‌های علایق را به پروفایل خود اضافه کنید.',
                'FEATURE_THEME_TITLE': 'تم تاریک/روشن',
                'FEATURE_THEME_DESC': 'تم مورد علاقه خود را برای چت راحت انتخاب کنید.',
                'SECTION_FEATURES_TITLE': 'ویژگی‌های قدرتمند',
                'SECTION_FEATURES_SUB': 'همه چیز برای ارتباطات معنادار',
                'SECTION_ABOUT_TITLE': 'درباره چت‌می',
                'SECTION_ABOUT_SUB': 'شکستن موانع، ساختن ارتباطات',
                'MISSION_TITLE': 'ماموریت ما',
                'MISSION_DESC': 'چت‌می با یک چشم‌انداز ساده اما قدرتمند ایجاد شد: اتصال مردم از همه اقشار زندگی، صرف نظر از زبان یا مکان.',
                'JOIN_TITLE': 'به جامعه ما بپیوندید',
                'JOIN_DESC': 'چه به دنبال تمرین زبان جدید باشید، چه پیدا کردن دوستانی از سراسر جهان، چت‌می برای شماست.',
                'CTA_JOIN': 'شروع سفر',
                'STATS_USERS': 'کاربران فعال',
                'STATS_COUNTRIES': 'کشورها',
                'STATS_CONVERSATIONS': 'گفتگوها',
                'STATS_LANGUAGES': 'زبان‌ها',
                'FOOTER_RIGHTS': '© 2025 Chatme. تمامی حقوق محفوظ است.'
            },
            'AUTH': {
                'WELCOME': 'به چت‌می خوش آمدید',
                'SUBTITLE': 'با افرادی که هم‌فرکانس شما هستند ارتباط برقرار کنید',
                'CONTINUE_GOOGLE': 'ادامه با گوگل',
                'SIGNING_IN': 'در حال ورود...',
                'OR': 'یا',
                'REAL_TIME_TRANS': 'ترجمه بلادرنگ',
                'SMART_MATCHING': 'تطبیق هوشمند',
                'PRIVACY_FIRST': 'اول حریم خصوصی',
                'TERMS_AGREE': 'با ورود به سیستم، شما با',
                'TERMS': 'شرایط',
                'AND': 'و',
                'PRIVACY': 'سیاست حفظ حریم خصوصی'
            },
            'NAV': {
                'DASHBOARD': 'داشبورد',
                'CHAT': 'چت',
                'PROFILE': 'پروفایل',
                'LOGOUT': 'خروج',
                'LOGIN': 'ورود',
                'LANGUAGE': 'زبان',
                'MESSAGES': 'پیام‌ها',
                'EXPLORE': 'کاوش',
                'GUESTS': 'مهمانان',
                'GAMES': 'بازی‌ها',
                'ADMIN_PANEL': 'پنل مدیریت',
                'CONTACT_ADMIN': 'تماس با مدیر',
                'LIGHT_MODE': 'حالت روشن',
                'DARK_MODE': 'حالت تاریک'
            },
            'PROFILE': {
                'ABOUT': 'درباره من',
                'LANGUAGES': 'زبان‌ها',
                'NATIVE': 'مادری',
                'LEARNING': 'در حال یادگیری',
                'INTERESTS': 'علایق',
                'COMMENTS_RATINGS': 'نظرات و امتیازات',
                'RATE_USER': 'امتیاز به کاربر',
                'WRITE_COMMENT_OPTIONAL': 'نظر بنویسید (اختیاری)...',
                'SUBMIT_RATING': 'ثبت امتیاز',
                'ADD_COMMENT': 'افزودن نظر',
                'WRITE_COMMENT': 'نظر بنویسید...',
                'ADD_COMMENT_BTN': 'افزودن',
                'REPLY': 'پاسخ',
                'SEND': 'ارسال',
                'SHOW': 'نمایش',
                'HIDE': 'پنهان کردن',
                'REPLIES': 'پاسخ‌ها',
                'REPLY_SINGULAR': 'پاسخ',
                'NO_COMMENTS': 'هنوز نظری ثبت نشده است.',
                'SEND_MESSAGE': 'ارسال پیام'
            },
            'CHAT': {
                'SELECT_CONVERSATION': 'انتخاب گفتگو',
                'START_NOW': 'همین حالا شروع کنید',
                'WELCOME': 'به چت‌می خوش آمدید',
                'WELCOME_SUB': 'یک گفتگو را انتخاب کنید یا برای شروع چت یک دوست جدید پیدا کنید.',
                'TYPE_MESSAGE': 'پیام بنویسید...',
                'ONLINE': 'آنلاین',
                'OFFLINE': 'آفلاین',
                'CHAT_PARTNER': 'هم‌صحبت',
                'EMPTY_STATE_TITLE': 'به چت‌می خوش آمدید',
                'EMPTY_STATE_DESC': 'یک گفتگو را انتخاب کنید یا برای شروع چت یک دوست جدید پیدا کنید.',
                'SEND_IMAGE': 'ارسال تصویر',
                'SEND_STICKER': 'ارسال استیکر',
                'VOICE_MESSAGE': 'پیام صوتی',
                'RATING_TITLE': 'امتیاز به تجربه',
                'RATING_Question': 'گفتگوی شما چطور بود؟',
                'RATING_COMMENT_PLACEHOLDER': 'نظری دارید؟',
                'SKIP': 'رد کردن',
                'SUBMIT': 'ثبت',
                'REQUEST_TITLE': 'درخواست چت جدید',
                'REQUEST_DESC': 'می‌خواهد با شما چت کند!',
                'DECLINE': 'رد کردن',
                'ACCEPT': 'پذیرفتن',
                'FIND_MATCH_TITLE': 'یافتن هم‌صحبت',
                'GENDER': 'جنسیت',
                'LOCATION': 'مکان',
                'ANY_LOCATION': 'هر مکانی',
                'ONLINE_ONLY': 'فقط آنلاین',
                'SEARCH': 'جستجو',
                'ANY_GENDER': 'هر جنسیتی',
                'MALE': 'مرد',
                'FEMALE': 'زن',
                'VALIDATION_MESSAGE': 'لطفاً ابتدا اطلاعات پروفایل خود (زبان‌ها و علایق) را تکمیل کنید تا بتوانید از این ویژگی استفاده کنید.',
                'COMPLETE_PROFILE': 'تکمیل پروفایل'
            },
            'DASHBOARD': {
                'ONLINE': 'آنلاین',
                'PROFILE': 'پروفایل',
                'FIND_MATCH': 'یافتن هم‌صحبت',
                'STATUS_ONLINE': 'آنلاین'
            },
            'COMMON': {
                'SAVE': 'ذخیره',
                'CANCEL': 'لغو',
                'CLOSE': 'بستن',
                'SUBMIT': 'ارسال',
                'SEARCH_PLACEHOLDER': 'جستجو...',
                'NO_RESULTS': 'نتیجه‌ای یافت نشد'
            }
        }
    };

    supportedLanguages = [
        { code: 'en', name: 'English', flag: '🇺🇸' },
        { code: 'ru', name: 'Русский', flag: '🇷🇺' },
        { code: 'tj', name: 'Тоҷикӣ', flag: '🇹🇯' },
        { code: 'ar', name: 'العربية', flag: '🇸🇦' },
        { code: 'es', name: 'Español', flag: '🇪🇸' },
        { code: 'fr', name: 'Français', flag: '🇫🇷' },
        { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
        { code: 'zh', name: '中文', flag: '🇨🇳' },
        { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
        { code: 'fa', name: 'فارسی', flag: '🇮🇷' }
    ];

    translate(key: string): string {
        const lang = this.currentLang();
        const keys = key.split('.');
        let result = this.translations[lang] || this.translations['en'];

        for (const k of keys) {
            if (result && result[k]) {
                result = result[k];
            } else {
                // Fallback to English if key missing in current language
                let fallback = this.translations['en'];
                for (const fk of keys) {
                    if (fallback && fallback[fk]) {
                        fallback = fallback[fk];
                    } else {
                        return key; // Return key if not found at all
                    }
                }
                return fallback;
            }
        }
        return result;
    }

    setLanguage(code: string) {
        if (this.translations[code] || this.supportedLanguages.find(l => l.code === code)) {
            this.currentLang.set(code);
            localStorage.setItem('lang', code);
            // Some languages are RTL
            this.updateLayoutDirection(code);
        }
    }

    getCurrentLanguage() {
        return this.currentLang();
    }

    private updateLayoutDirection(code: string) {
        const isRtl = code === 'ar' || code === 'fa';
        document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
        document.documentElement.lang = code;
    }

    // Initialize layout direction on service creation
    constructor() {
        this.updateLayoutDirection(this.currentLang());
    }
}
